-- --------------------------------------------------------
-- Servidor:                     192.168.0.101
-- Versão do servidor:           8.0.16 - MySQL Community Server - GPL
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando dados para a tabela ocorrencias.clientes: ~487 rows (aproximadamente)
DELETE FROM `clientes`;
/*!40000 ALTER TABLE `clientes` DISABLE KEYS */;
INSERT INTO `clientes` (`Código`, `Nome`, `Endereço`, `Número`, `Bairro`, `Cidade`, `UF`, `CEP`, `email`, `Telefone`, `Celular`, `Contato`, `Técnico`, `Complemento`, `Foto`) VALUES
	(1, 'Acir', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '51 99741780', NULL, 'Acir', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAcir.jpg'),
	(2, 'Adalto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05196839052', NULL, 'Adalto', 'Facco', NULL, NULL),
	(3, 'Adriane Alves Engel Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Adriane', 'Facco', NULL, NULL),
	(4, 'Advogado DIEGO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92538771', NULL, 'Advogado', 'Facco', NULL, NULL),
	(5, 'Alan camargo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94540681', NULL, 'Alan', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAlan Camargo.jpg'),
	(6, 'Albino Rossi Filho', 'Curitiba - Pr', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Albino', 'Facco', NULL, NULL),
	(7, 'Aldry Maciel', NULL, NULL, NULL, NULL, NULL, NULL, 'aldry.maciel@facebook.com', '84818201', NULL, 'Aldry', 'Facco', NULL, NULL),
	(8, 'Alessandro Ghedin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5499383414', '92465441', 'Alessando', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAlessandro Ghedin.jpg'),
	(9, 'Alexandre Campanella- Advogado', 'Av.Dorival Cândido Luz de Oliveira', 7400, 'Bom Principio', 'Gravataí', 'RS', '94070-000', 'akzadvogados@hotmail.com', '34889405', '94634399', 'Alexandre', 'Facco', '05184169111', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAlexandre Campanella- Advogado.jpg'),
	(10, 'Alexandre Lopes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Alexandre', 'Facco', NULL, NULL),
	(11, 'Aline UnesulTur', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '32848100', NULL, 'Aline', 'Facco', NULL, NULL),
	(12, 'Aline', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33334747', '91497215', 'Aline', 'Facco', NULL, NULL),
	(13, 'Aline Cristina Nunes Haack', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34411474', '94423288', 'Aline Cristina', 'Facco', NULL, NULL),
	(14, 'Altair Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30266219', '91484353', 'Altair', 'Facco', NULL, NULL),
	(15, 'Alvarez', 'Rua Santa Cecilia', 517, 'Vila City', 'Cachoeirinha', 'RS', '94935-130', 'alvarezatacado@yahoo.com.br', '5134703878', '5134712390', 'Alvarez', 'Facco', '05199415994', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAlvarez.jpg'),
	(16, 'amanda leda', NULL, NULL, NULL, NULL, NULL, NULL, 'amandinha.al@gmail.com', NULL, NULL, 'amanda', 'Facco', NULL, NULL),
	(17, 'Ana Moraes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05134690828', NULL, 'Ana', 'Facco', NULL, NULL),
	(18, 'Ana Paula Keunecke Machado', NULL, NULL, NULL, NULL, NULL, NULL, 'anapaulakm@brturbo.com.br', NULL, NULL, 'Ana', 'Facco', NULL, NULL),
	(19, 'Ana Maria Da Silveira Machado - Cliente', 'Rua Bonsucesso', 979, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-490', NULL, NULL, '985077508', 'Ana Maria', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAna Maria Da Silveira Machado - Cliente.jpg'),
	(20, 'Ana Paula Keunecke Machado', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34885977', '91030196', 'Ana Paula', 'Facco', NULL, NULL),
	(21, 'Anatan Raupp', NULL, NULL, NULL, NULL, NULL, NULL, 'anatanraupp@gmail.com', NULL, NULL, 'Anatan', 'Facco', NULL, NULL),
	(22, 'Anatercia concato', NULL, NULL, NULL, NULL, NULL, NULL, 'anaconcato@ig.com.br', '34691365', '91139045', 'Anatercia', 'Facco', '81803043', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAnatercia concato.jpg'),
	(23, 'Andersom - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05181179582', NULL, 'Andersom', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndersom - Cliente.jpg'),
	(24, 'Anderson Lambert', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Anderson', 'Facco', NULL, NULL),
	(25, 'Andiara Martins Vilas Boas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84916765', NULL, 'Andiara', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndiara Martins Vilas Boas.jpg'),
	(26, 'Andre Pini', 'Rua Biagio Marchetti', 221, NULL, NULL, NULL, NULL, NULL, '11971520768', NULL, 'Andre', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndre Pini.jpg'),
	(27, 'Angela', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '86050256', NULL, 'Angela', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAngela.jpg'),
	(28, 'Angela padaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5191015877', NULL, 'Angela', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAngela padaria.jpg'),
	(29, 'Angelo Marcio Barreto', NULL, NULL, NULL, NULL, NULL, NULL, 'angelombarreto@gmail.com', '01184098723', NULL, 'Angelo', 'Facco', NULL, NULL),
	(30, 'Aramis', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84451161', NULL, 'Aramis', 'Facco', NULL, NULL),
	(31, 'Aris Orlando da Silva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30513365', '81647739', 'Aris', 'Facco', NULL, NULL),
	(32, 'Aroldo Regis Mendes Silvei', 'Canoas', NULL, NULL, NULL, NULL, NULL, 'aroldosilveira@gmail.com', '34274586', '82200200', 'Aroldo', 'Facco', '81103050', NULL),
	(33, 'Artur Dona Alzira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33817741', NULL, 'Artur', 'Facco', NULL, NULL),
	(34, 'Azambuja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '36921311', '99822138', 'Azambuja', 'Facco', NULL, NULL),
	(35, 'Banco Itau', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '01123220989', '21083085', 'Banco', 'Facco', '05121083050', NULL),
	(36, 'Banda Mithra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5192101238', NULL, 'Banda', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBanda Mithra.jpg'),
	(37, 'Barbara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81911203', NULL, 'Barbara', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBarbara.jpg'),
	(38, 'Bauru Da Tribo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '83171653', '92105380', 'Bauru', 'Facco', '95425522', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBauru Da Tribo.jpg'),
	(39, 'Beethoven Dalton de Paula', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3288614354', NULL, 'Beethoven', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBeethoven Dalton de Paula.jpg'),
	(40, 'Beloni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05191730698', '05185365073', 'Beloni', 'Facco', NULL, NULL),
	(41, 'Benhur Brum Costa', NULL, NULL, NULL, NULL, NULL, NULL, 'benhurstrike@bol.com.br', NULL, NULL, 'Benhur', 'Facco', NULL, NULL),
	(42, 'Braian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92508002', NULL, 'Braian', 'Facco', NULL, NULL),
	(43, 'Bruna Konrath', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '82033988', NULL, 'Bruna', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBruna Konrath.jpg'),
	(44, 'Caixa Postal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Caixa', 'Facco', NULL, NULL),
	(45, 'Caixa - Mari Camila - Tais', NULL, NULL, NULL, NULL, NULL, NULL, 'mari.muller@caixa.gov.br', '21035830', '21035801', 'Caixa - Mari', 'Facco', '21035800', NULL),
	(46, 'Carem Fisioterapeuta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33418962', '91024890', 'Carem', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCarem Fisioterapeuta.jpg'),
	(47, 'Carla Bertoletti', NULL, NULL, NULL, NULL, NULL, NULL, 'carla@fullpromo.com.br', NULL, NULL, 'Carla', 'Facco', NULL, NULL),
	(48, 'Carlinhos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05199539453', NULL, 'Carlinhos', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCarlinhos.jpg'),
	(49, 'Carlos Alberto Tranin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Carlos Alberto', 'Facco', NULL, NULL),
	(50, 'Carol Facco', NULL, NULL, NULL, NULL, NULL, NULL, 'carol_facco@yahoo.com.br', '93052236', NULL, 'Carol', 'Facco', NULL, NULL),
	(51, 'Caroline  - Dilson Stein', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5535376116', NULL, 'Caroline -', 'Facco', NULL, NULL),
	(52, 'carrieee55142', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'carrieee55142', 'Facco', NULL, NULL),
	(53, 'Casa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34392279', '31374391', 'Casa', 'Facco', NULL, NULL),
	(54, 'Cassiana Bogoni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93787908', NULL, 'Cassiana', 'Facco', NULL, NULL),
	(55, 'Cebola', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85358723', NULL, 'Cebola', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCebola.jpg'),
	(56, 'celso macichonek', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'celso', 'Facco', NULL, NULL),
	(57, 'Celso Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1632382088', '016993975945', 'Celso', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCelso Oliveira.jpg'),
	(58, 'Centro Da Dor - GHC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33572140', NULL, 'Centro Da Dor', 'Facco', NULL, NULL),
	(59, 'Cesar Toniazzo Padeiro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Cesar Toniazzo', 'Facco', NULL, NULL),
	(60, 'Charles - Poli', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96373444', NULL, 'Charles', 'Facco', NULL, NULL),
	(61, 'Charles Tissiani - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5181195458', NULL, 'Charles Tissiani', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCharles Tissiani - Cliente.jpg'),
	(62, 'Chaves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92937714', NULL, 'Chaves', 'Facco', NULL, NULL),
	(63, 'Chico / Carina', NULL, NULL, NULL, NULL, NULL, NULL, 'chico@mfconect.com.br', '33481832', '91027636', 'Chico / Carina', 'Facco', NULL, NULL),
	(64, 'Cia do Ar Parapente', 'Rua Monte Castelo', 4004, NULL, 'Sapiranga', 'Rs', NULL, NULL, NULL, '84362092', 'Cia do Ar', 'Facco', '81243404', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCia do Ar Parapente.jpg'),
	(65, 'Clairton - Cliente', 'Rua Barão de Cotejipe', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', NULL, '5185684575', '(51)99973-4540', 'Clairton', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesClairton.jpg'),
	(66, 'Claiton', 'Av.Panamericana', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-330', 'claiton.backup@gmail.com', '98476935', '34697115', 'Pw:Claiton12345', 'Facco', '99226416', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesClaiton.jpg'),
	(67, 'Claudio Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11971678355', NULL, 'Claudio', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesClaudio Oliveira.jpg'),
	(68, 'Cleusa Rossato', NULL, NULL, NULL, NULL, NULL, NULL, 'cleusa.rossato@hotmail.com', '33401137', '05185651196', 'Cleusa', 'Facco', NULL, NULL),
	(69, 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94469176', 'Cliente', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCliente.jpg'),
	(70, 'Cliente1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05184946075', 'Cliente1', 'Facco', NULL, NULL),
	(71, 'Clodoaldo da Silva Fraga', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99877850', 'Clodoaldo', 'Facco', NULL, NULL),
	(72, 'Comida - Jane', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98920773', 'Comida', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesComida - Jane.jpg'),
	(73, 'Connect Lan House', 'Av.Panamericana', 808, NULL, 'Cachoeirinha', 'RS', NULL, 'connectlanhouse-rs@hotmail.com', '34393384', '81028609', 'Connect', 'Facco', NULL, NULL),
	(74, 'Connect Servicos', NULL, NULL, NULL, NULL, NULL, NULL, 'connectservicors@gmail.com', '86464205', '98601789', 'Connect', 'Facco', NULL, NULL),
	(75, 'Conserto TV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33382408', NULL, 'Conserto TV', 'Facco', NULL, NULL),
	(76, 'Cris', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84608537', NULL, 'Cris', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCris.jpg'),
	(77, 'Cristina - Cliente', 'Av.Panamericana', 1089, 'Parque da Matriz', 'Cacheirinha', 'RS', '94950-330', 'cristina.juju.connect@gmail.com', '84748067', '34698538', 'Cristina', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJuliana Correa.jpg'),
	(78, 'Daivis Tv', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '37792024', '92242008', 'Daivis', 'Facco', NULL, NULL),
	(79, 'DALVA SEGUROS', NULL, NULL, NULL, NULL, NULL, NULL, 'dalva@segurosdemoraes.com.br', NULL, NULL, 'DALVA', 'Facco', NULL, NULL),
	(80, 'Dani Prima', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '82620132', NULL, 'Dani', 'Facco', NULL, NULL),
	(81, 'Dani', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84134723', NULL, 'Dani', 'Facco', NULL, NULL),
	(82, 'Daniel - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84827504', NULL, 'Daniel', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDaniel - Cliente.jpg'),
	(83, 'Daniel Drapac do Amaral', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11984642285', NULL, 'Daniel Drapac', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDaniel Drapac do Amaral.jpg'),
	(84, 'Daniella Costa da Silva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '964883048', NULL, 'Daniella', 'Facco', NULL, NULL),
	(85, 'Danielle Madeira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85565894', NULL, 'Danielle', 'Facco', NULL, NULL),
	(86, 'Dario Cupertino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1182451229', NULL, 'Dario', 'Facco', NULL, NULL),
	(87, 'Delamir Solange de Barros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93264060', NULL, 'Delamir', 'Facco', NULL, NULL),
	(88, 'Dell Computadores', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05121045500', NULL, 'Dell', 'Facco', NULL, NULL),
	(89, 'Denis PAPAI do GABRIEL e MARIANA.', NULL, NULL, NULL, NULL, NULL, NULL, 'denis.maurer@gmail.com', NULL, NULL, 'Denis', 'Facco', NULL, NULL),
	(90, 'Denise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34694188', '84255350', 'Denise', 'Facco', NULL, NULL),
	(91, 'Dentista', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84751545', 'Dentista', 'Facco', NULL, NULL),
	(92, 'Desiree Mendes Ribeiro', 'Rua Botafogo', 700, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-080', 'desireemendesribeiro@gmail.com', '84102550', '83225267', 'Desiree', 'Facco', '94250693', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDesiree Mendes Ribeiro.jpg'),
	(93, 'Diego Azevedo', NULL, NULL, NULL, NULL, NULL, NULL, 'supercolonial@gmail.com', '34692588', '05134690935', 'Diego', 'Facco', '85192022', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDiego Azevedo.jpg'),
	(94, 'Dione Heineck', NULL, NULL, NULL, NULL, NULL, NULL, 'dioneheineck@hotmail.com', NULL, NULL, 'Dione', 'Facco', NULL, NULL),
	(95, 'Douglas G', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Douglas', 'Facco', NULL, NULL),
	(96, 'Douglas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93606511', '05191402893', 'Douglas', 'Facco', NULL, NULL),
	(97, 'Douglas Haack', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5192378228', NULL, 'Douglas', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDouglas Haack.jpg'),
	(98, 'Douglas ACE - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84577232', '91988309', 'Douglas ACE', 'Facco', NULL, NULL),
	(99, 'DPVAT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '02131220031', NULL, 'DPVAT', 'Facco', NULL, NULL),
	(100, 'Dr Faz Tudo do Brasil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1925137350', 'Dr Faz Tudo', 'Facco', NULL, NULL),
	(101, 'Edemar Pereira Junior', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91651857', NULL, 'Edemar', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEdemar Pereira Junior.jpg'),
	(102, 'Edimara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96138023', NULL, 'Edimara', 'Facco', NULL, NULL),
	(103, 'Edimilsom Konig', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81467187', '34711669', 'Edimilsom', 'Facco', NULL, NULL),
	(104, 'Edna Siva', 'Osasco - SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Edna', 'Facco', NULL, NULL),
	(105, 'Eduardo Azeredo', 'Av.Assis Brasil', 4320, 'Parquer São Sebastião', 'Porto Alegre', 'RS', '91110-000', NULL, '96189602', NULL, 'Eduardo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEduardo Azeredo.jpg'),
	(106, 'Eduardo Azeredo Da Rosa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96189602', NULL, 'Eduardo Azeredo', 'Facco', NULL, NULL),
	(107, 'Edvaldo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84047336', '32243192', 'Edvaldo', 'Facco', NULL, NULL),
	(108, 'Elenita Facco', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34391838', '94427972', 'Elenita', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesElenita Facco.jpg'),
	(109, 'Elis Regina Camargo Dos Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05192997051', NULL, 'Elis Regina Camargo', 'Facco', NULL, NULL),
	(110, 'Elisabete - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34716070', NULL, 'Elisabete', 'Facco', NULL, NULL),
	(111, 'Elizete Imobiliaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34701643', '05181826593', 'Elizete', 'Facco', '05193013244', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesElizete Imobiliaria.jpg'),
	(112, 'Ellen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99007975', NULL, 'Ellen', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEllen.jpg'),
	(113, 'Emerson Miguel da Silva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Emerson', 'Facco', NULL, NULL),
	(114, 'Ensel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34701001', 'Ensel', 'Facco', NULL, NULL),
	(115, 'Eny Hsu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11959850008', NULL, 'Eny', 'Facco', NULL, NULL),
	(116, 'Erico Arend', NULL, NULL, NULL, NULL, NULL, NULL, 'taero@ibest.com.br', '34965839', NULL, 'Erico', 'Facco', NULL, NULL),
	(117, 'esthevan leppa', NULL, NULL, NULL, NULL, NULL, NULL, 'esthevanmadrid20@gmail.com', NULL, NULL, 'esthevan', 'Facco', NULL, NULL),
	(118, 'Evandro Marchizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5182200072', NULL, 'Evandro', 'Facco', NULL, NULL),
	(119, 'Fabiana Edwiges Agnelo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1991158318', NULL, 'Fabiana Edwiges', 'Facco', NULL, NULL),
	(120, 'Fabiane Rocha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05191728961', NULL, 'Fabiane', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFabiane Rocha.jpg'),
	(121, 'Fabiano S.Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fabiano', 'Facco', NULL, NULL),
	(122, 'Fabiano Schuingel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05137486002', '05199041851', 'Fabiano', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFabiano Schuingel.jpg'),
	(123, 'Fabio Martins', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fabio', 'Facco', NULL, NULL),
	(124, 'Fabio dos Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11996615106', NULL, 'Fabio', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFabio dos Santos.jpg'),
	(125, 'Farby', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85046950', 'Farby', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFarby.jpg'),
	(126, 'Felipe Rodrigo Araujo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Felipe Rodrigo', 'Facco', NULL, NULL),
	(127, 'Fernanda Martins', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92431986', NULL, 'Fernanda', 'Facco', NULL, NULL),
	(128, 'fernanda rodrigues', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'fernanda', 'Facco', NULL, NULL),
	(129, 'Fernando Faro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '986936802', NULL, 'Fernando', 'Facco', NULL, NULL),
	(130, 'Festa CHIC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96195134', NULL, 'Festa', 'Facco', NULL, NULL),
	(131, 'Francine', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92034488', NULL, 'Francine', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFrancine.jpg'),
	(132, 'Francisco Feitosa Pereira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11999558428', NULL, 'Francisco Feitosa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFrancisco Feitosa Pereira.jpg'),
	(133, 'Franco Laus - Advogado', NULL, NULL, NULL, NULL, NULL, NULL, 'francolaus@ig.com.br', '84115964', '34704209', 'Franco Laus', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFranco Laus - Advogado.jpg'),
	(134, 'Franklin - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94174948', NULL, 'Franklin', 'Facco', NULL, NULL),
	(135, 'Fredson Pereira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fredson', 'Facco', NULL, NULL),
	(136, 'Gabriel Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, 'gabrieloliveira131189@gmail.com', NULL, NULL, 'Gabriel', 'Facco', NULL, NULL),
	(137, 'Gabriel De Almeida Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '97403724', NULL, 'Gabriel', 'Facco', NULL, NULL),
	(138, 'Gabriel Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, 'gabrieloliveira131189@gmail.com', NULL, NULL, 'Gabriel', 'Facco', NULL, NULL),
	(139, 'Gabriela Ragazzon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91927669', '93032100', 'Gabriela', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGabriela Ragazzon.jpg'),
	(140, 'Garcia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5198701387', '5185159085', 'Garcia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGarcia.jpg'),
	(141, 'Geandra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34414419', NULL, 'Geandra', 'Facco', NULL, NULL),
	(142, 'Gerson Alves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4188481845', NULL, 'Gerson', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGerson Alves.jpg'),
	(143, 'Gerson Pereira Alves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05197594031', NULL, 'Gerson', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGerson Pereira Alves.jpg'),
	(144, 'Gilberto Teixeira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gilberto', 'Facco', NULL, NULL),
	(145, 'Gilmar Tavares Lira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Gilmar', 'Facco', NULL, NULL),
	(146, 'Gisele Pavan Franco', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92159729', NULL, 'Gisele', 'Facco', NULL, NULL),
	(147, 'Gislaine Roger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21018390', '96284608', 'Gislaine', 'Facco', NULL, NULL),
	(148, 'Gordines', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '86097383', NULL, 'Gordines', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGordines.jpg'),
	(149, 'Grupo tatoo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Grupo', 'Facco', NULL, NULL),
	(150, 'Gustavo Dorneles', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5195061365', NULL, 'Gustavo', 'Facco', NULL, NULL),
	(151, 'Gustavo De Aguiar', NULL, NULL, NULL, NULL, NULL, NULL, 'gustavo@locamotos.com.br', '89045500', NULL, 'Gustavo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGustavo De Aguiar.jpg'),
	(152, 'GVT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '04130252525', '04130856518', 'GVT', 'Facco', NULL, NULL),
	(153, 'GVT - Valdimir', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05191304779', '05191154378', 'GVT', 'Facco', '0800 601 5005', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGVT - Valdimir.jpg'),
	(154, 'Havi Strzalkowski Wedge', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81568170', '80582185', 'Havi', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesHavi Strzalkowski Wedge.jpg'),
	(155, 'HDI Seguros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '08007015430', '08007077724', 'HDI', 'Facco', NULL, NULL),
	(156, 'Helena Terezinha Vogel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34694099', '81450364', 'Helena', 'Facco', NULL, NULL),
	(157, 'Henrique rodrigues', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Henrique', 'Facco', NULL, NULL),
	(158, 'Humberto', 'Rua Guarani', 152, NULL, 'Cachoeirinha', 'RS', NULL, NULL, '34701517', '81594712', 'Humberto', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesHumberto.jpg'),
	(159, 'idelma', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05133411193', '84880494', 'idelma', 'Facco', '96559262', NULL),
	(160, 'Inquilino Leandro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05194583246', NULL, 'Inquilino', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesInquilino Leandro.jpg'),
	(161, 'Isaac Silveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91000757', NULL, 'Isaac', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesIsaac Silveira.jpg'),
	(162, 'Itau - Michele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05121083050', '21083085', 'Itau - Michele', 'Facco', NULL, NULL),
	(163, 'Itaucard', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30033030', NULL, 'Itaucard', 'Facco', NULL, NULL),
	(164, 'Ivan Clever', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34699753', '84943450', 'Ivan', 'Facco', '99033129', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesIvan Clever.jpg'),
	(165, 'Jaderson Marques Gomes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Jaderson', 'Facco', NULL, NULL),
	(166, 'jairo schuler', NULL, NULL, NULL, NULL, NULL, NULL, 'jairoschuler@gmail.com', NULL, NULL, 'jairo', 'Facco', NULL, NULL),
	(167, 'JANICE e ROGERIO', NULL, NULL, NULL, NULL, NULL, NULL, 'silveira.janice@bol.com.br', NULL, NULL, 'JANICE', 'Facco', NULL, NULL),
	(168, 'Janrie Ribeiro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94492146', NULL, 'Janrie', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJanrie Ribeiro.jpg'),
	(169, 'Jaqueline Teixeira Da Silva', NULL, NULL, NULL, NULL, NULL, NULL, 'jaklyne_silva@hotmail.com', '30202186', '98651919', 'Jaqueline Teixeira', 'Facco', '84629644', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesjaqueline teixeira da silva.jpg'),
	(170, 'Jessica Petrillo Brum', 'Copacabana', 195, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-575', 'jessicapetrillobrum@gmail.com', '34693978', '96268855', 'Jessica', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJessica Petrillo Brum.jpg'),
	(171, 'Jessica - Prima Desiree', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '+55 51 84937946', NULL, 'Jessica -', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJessica - Prima Desiree.jpg'),
	(172, 'Joel Transportadora', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92569150', NULL, 'Joel', 'Facco', NULL, NULL),
	(173, 'Jorge - Lava Carro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85550791', '85046747', 'Jorge -', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJorge - Lava Carro.jpg'),
	(174, 'Jose - Ensel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '97984529', NULL, 'Jose', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJose - Ensel.jpg'),
	(175, 'Jose Milare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5,51196E+11', NULL, 'Jose', 'Facco', NULL, NULL),
	(176, 'Jose Aurelio Pereira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Jose Aurelio', 'Facco', NULL, NULL),
	(177, 'Jose Claiton Guerra Bidinoto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Jose Claiton Guerra', 'Facco', NULL, NULL),
	(178, 'jose Filho Chavier', 'Rua Santo, 118', 118, NULL, NULL, NULL, NULL, NULL, '1391400904', NULL, 'jose Filho', 'Facco', NULL, NULL),
	(179, 'Josi Santos', NULL, NULL, NULL, NULL, NULL, NULL, 'josyanesantos08@yahoo.com.br', NULL, NULL, 'Josi', 'Facco', NULL, NULL),
	(180, 'Josi - Alvarez', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34717259', '85473269', 'Josi', 'Facco', '+55 51 92834896', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJosi - Alvarez.jpg'),
	(181, 'Josi Santos', NULL, NULL, NULL, NULL, NULL, NULL, 'josyanesantos08@yahoo.com.br', NULL, NULL, 'Josi', 'Facco', NULL, NULL),
	(182, 'Josy [GFBPA]', NULL, NULL, NULL, NULL, NULL, NULL, 'josyanesantos08@yahoo.com.br', NULL, NULL, 'Josy', 'Facco', NULL, NULL),
	(183, 'Juan carlos Orlando Aguilar Rodriguez', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Juan carlos Orlando', 'Facco', NULL, NULL),
	(184, 'Juarez Massaia', NULL, NULL, NULL, NULL, NULL, NULL, 'juarezmassaia48@gmail.com', '92002731', NULL, 'Juarez', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJuarez Massaia.jpg'),
	(185, 'JUAREZ MASSAIA', NULL, NULL, NULL, NULL, NULL, NULL, 'juarezmassaia48@gmail.com', NULL, NULL, 'JUAREZ', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJuarez Massaia.jpg'),
	(186, 'Juciane -  Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30202072', NULL, 'Juciane', 'Facco', NULL, NULL),
	(187, 'Julia Souza', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4896677242', NULL, 'Julia', 'Facco', NULL, NULL),
	(188, 'Juliano Modernel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05185758033', NULL, 'Juliano', 'Facco', NULL, NULL),
	(189, 'Juliano Forte', NULL, NULL, NULL, NULL, NULL, NULL, 'julianoforte@click21.com.br', NULL, NULL, 'Juliano', 'Facco', NULL, NULL),
	(190, 'Julio Cesar Altafini', 'Porto Alegre / RS', NULL, NULL, NULL, NULL, NULL, 'julio.altafini@terra.com.br', '96188001', NULL, 'Julio', 'Facco', NULL, NULL),
	(191, 'Jussara', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81373756', NULL, 'Jussara', 'Facco', NULL, NULL),
	(192, 'Karin Bernsmuller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05134413605', NULL, 'Karin', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesKarin Bernsmuller.jpg'),
	(193, 'Karine - Fantasias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5,55193E+11', NULL, 'Karine', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesKarine - Fantasias.jpg'),
	(194, 'Karine Martins - Maicon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '82792738', NULL, 'Karine Martins', 'Facco', NULL, NULL),
	(195, 'Kawasaki IESA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30258558', NULL, 'Kawasaki', 'Facco', NULL, NULL),
	(196, 'Kedi - Filha Da Caren', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05191858820', NULL, 'Kedi - Filha', 'Facco', NULL, NULL),
	(197, 'Kelly Prima Desi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05193500969', NULL, 'Kelly', 'Facco', NULL, NULL),
	(198, 'Kemer Nogueira de Assis', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kemer', 'Facco', NULL, NULL),
	(199, 'Kika', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91457920', NULL, 'Kika', 'Facco', NULL, NULL),
	(200, 'Lais', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93996061', NULL, 'Lais', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLais.jpg'),
	(201, 'Lau Rodrigues', NULL, NULL, NULL, NULL, NULL, NULL, 's2_lau@hotmail.com', NULL, NULL, 'Lau', 'Facco', NULL, NULL),
	(202, 'LBV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33257000', NULL, 'LBV', 'Facco', NULL, NULL),
	(203, 'Leandro Strzalkowski', 'Rua Itaqui', 477, NULL, NULL, NULL, NULL, NULL, '30415650', '80151353', 'Leandro', 'Facco', '80151353', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLeandro Strzalkowski.jpg'),
	(204, 'Leandro Conquiste', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91239319', NULL, 'Leandro', 'Facco', NULL, NULL),
	(205, 'Leandro Bueno Leite', NULL, NULL, NULL, NULL, NULL, NULL, 'leandro.bueno.l@gmail.com', '84909770', '86253415', 'Leandro', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLeandro Bueno Leite.jpg'),
	(206, 'Leci Marcio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34708118', NULL, 'Leci Marcio', 'Facco', NULL, NULL),
	(207, 'Lee Schneider', NULL, NULL, NULL, NULL, NULL, NULL, 'lepowergirl@hotmail.com', NULL, NULL, 'Lee', 'Facco', NULL, NULL),
	(208, 'Leomar - Campanella', NULL, NULL, NULL, NULL, NULL, NULL, 'leomar@masternetrs.com.br', '99381003', NULL, 'Leomar', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLeomar - Campanella.jpg'),
	(209, 'Leonardo Estauber', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05184417514', NULL, 'Leonardo', 'Facco', NULL, NULL),
	(210, 'Leonardo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05192703559', NULL, 'Leonardo', 'Facco', NULL, NULL),
	(211, 'Lesli siqueira', NULL, NULL, NULL, NULL, NULL, NULL, 'lesli-siqueira@hotmail.com', NULL, NULL, 'Lesli', 'Facco', NULL, NULL),
	(212, 'Leticia Julans', '1630 Bulle, FR, Suisse', NULL, NULL, NULL, NULL, NULL, NULL, '41786321550', NULL, 'Leticia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLeticia Julans.jpg'),
	(213, 'Liciane Pelicoli', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84778202', '92875535', 'Liciane', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLiciane Pelicoli.jpg'),
	(214, 'Lisiane Cougo', NULL, NULL, NULL, NULL, NULL, NULL, 'lidianerossatotti@hotmail.com', '96625959', '85893380', 'Lisiane', 'Facco', '82179013', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLisiane Cougo.jpg'),
	(215, 'Lisiani Eberhardt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91253549', NULL, 'Lisiani', 'Facco', NULL, NULL),
	(216, 'Lorena - Campanella', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5182879041', NULL, 'Lorena', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLorena - Campanella.jpg'),
	(217, 'Lorival', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96418118', NULL, 'Lorival', 'Facco', NULL, NULL),
	(218, 'Lucas - Distribuidora', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05199921115', NULL, 'Lucas', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLucas - Distribuidora.jpg'),
	(219, 'Lucas - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93242710', NULL, 'Lucas', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLucas - Cliente.jpg'),
	(220, 'lucasalves', NULL, NULL, NULL, NULL, NULL, NULL, 'lucasalves@ferreiramaia.com', NULL, NULL, 'lucasalves', 'Facco', NULL, NULL),
	(221, 'Luciana da Silva Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33877417', '99576262', 'Luciana', 'Facco', NULL, NULL),
	(222, 'Luciano Voguel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93953092', NULL, 'Luciano', 'Facco', NULL, NULL),
	(223, 'Luciano Arcanjo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Luciano', 'Facco', NULL, NULL),
	(224, 'Luciano Autqueviezc da Silva', 'Rua F', 212, 'Parque madepinho', NULL, NULL, NULL, NULL, '5134474852', NULL, 'Luciano', 'Facco', NULL, NULL),
	(225, 'Lucila Fernandes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91722650', '81377258', 'Lucila', 'Facco', '91805908', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLucila Fernandes.jpg'),
	(226, 'Luis Carlos Brites Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Luis', 'Facco', NULL, NULL),
	(227, 'Luis Gilberto Costa - Pai do Ace', 'Copacabana', 135, 'Parque da Matriz', 'Cachoeirinha', 'RS', '95950-575', NULL, '5134697073', '51985649670', 'Luis', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuis Gilberto Costa-Pai Ace.jpg'),
	(228, 'Luis - Francis', 'Rua Rio Claro', 126, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-450', 'loso.fra@hotmail.com', '5184107729', '5134712250', 'Luis', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuis - Francis.jpg'),
	(229, 'Luis Fernando Schuller', NULL, NULL, NULL, NULL, NULL, NULL, 'schuler.luis@yahoo.com.br', '92814136', NULL, 'Luis', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuis Fernando Schuller.jpg'),
	(230, 'Luis Osorio Francisco', NULL, NULL, NULL, NULL, NULL, NULL, 'loso.fra@hotmail.com', NULL, NULL, 'Luis', 'Facco', NULL, NULL),
	(231, 'Luis - Juridico IMAMA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '97511844', NULL, 'Luis -', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuis - Juridico IMAMA.jpg'),
	(232, 'Luis Carlos Machado Araujo', 'Adelino Ferreira Jardim', 1, NULL, 'Porto Alegre', 'RS', NULL, NULL, '33669914', '98020332', 'Luis Carlos', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuis Carlos Machado Araujo.jpg'),
	(233, 'Luiz - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99701466', NULL, 'Luiz', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuiz - Cliente.jpg'),
	(234, 'Luiz Fernando Boscolo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1194300408', NULL, 'Luiz Fernando', 'Facco', NULL, NULL),
	(235, 'Lurdes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4896469437', NULL, 'Lurdes', 'Facco', NULL, NULL),
	(236, 'Luzimar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '97129644', NULL, 'Luzimar', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLuzimar.jpg'),
	(237, 'Mafia Canina', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84048442', NULL, 'Mafia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMafia Canina.jpg'),
	(238, 'Maramello Pizzaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34690102', 'Maramello', 'Facco', NULL, NULL),
	(239, 'Marcello Nakazato', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1182438327', NULL, 'Marcello', 'Facco', NULL, NULL),
	(240, 'MARCELO ACEDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MARCELO', 'Facco', NULL, NULL),
	(241, 'Marcelo Vieira', 'Avenida Marica, Bloco 2/401 - Colubande - RJ', 448, NULL, NULL, NULL, NULL, NULL, '2177335797', NULL, 'Marcelo', 'Facco', NULL, NULL),
	(242, 'Marcelo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94232005', '05192440247', 'Marcelo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarcelo.jpg'),
	(243, 'Marcelo Maciel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11964345456', NULL, 'Marcelo', 'Facco', NULL, NULL),
	(244, 'Marcio Alves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Marcio', 'Facco', NULL, NULL),
	(245, 'Marcio Lopes Vargas', 'Cassino - Rio Grande, RS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Marcio', 'Facco', NULL, NULL),
	(246, 'Marcio Henrique - Gugu', 'Barão de Cotegipe', 186, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', 'marciohenriquegugu@gmail.com', '994638996', NULL, 'Marcio', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarcio Henrique.jpg'),
	(247, 'Marco Savoy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Marco', 'Facco', NULL, NULL),
	(248, 'Maria Silva', NULL, NULL, NULL, NULL, NULL, NULL, 'dra.graca@hotmail.com', NULL, NULL, 'Maria', 'Facco', NULL, NULL),
	(249, 'Maria Isabel Posenatto Parmagnani', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria Isabel', 'Facco', NULL, NULL),
	(250, 'Marisa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05189271164', NULL, 'Marisa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarisa.jpg'),
	(251, 'Marisa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98265635', NULL, 'Marisa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarisa.jpg'),
	(252, 'Maristela', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '04792677789', NULL, 'Maristela', 'Facco', NULL, NULL),
	(253, 'Maritima Seguros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99798110', '30213500', 'Maritima', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMaritima Seguros.jpg'),
	(254, 'Marlise Droves', NULL, NULL, NULL, NULL, NULL, NULL, 'lizehdroves@gmail.com', '051 84166945', '051 96858410', 'Marlise', 'Facco', '85244339', NULL),
	(255, 'Marlon Droves', NULL, NULL, NULL, NULL, NULL, NULL, 'marlondroves@gmail.com', '85232825', NULL, 'Marlon', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarlon Droves.jpg'),
	(256, 'Mauricio - Keti', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05182112010', NULL, 'Mauricio', 'Facco', NULL, NULL),
	(257, 'Melissa Trevisan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99029756', NULL, 'Melissa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMelissa Trevisan.jpg'),
	(258, 'Micael Concato', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05193010786', NULL, 'Micael', 'Facco', NULL, NULL),
	(259, 'Michel - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '97970784', NULL, 'Michel', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMichel - Cliente.jpg'),
	(260, 'Michelle Heineck Layerle', NULL, NULL, NULL, NULL, NULL, NULL, 'michellelayerle@gmail.com', NULL, NULL, 'Michelle', 'Facco', NULL, NULL),
	(261, 'Milena', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84724401', NULL, 'Milena', 'Facco', NULL, NULL),
	(262, 'Milta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34070166', NULL, 'Milta', 'Facco', NULL, NULL),
	(263, 'Miltinho Vilas Boas', NULL, NULL, NULL, NULL, NULL, NULL, 'minerobnd57@gmail.com', NULL, NULL, 'Miltinho', 'Facco', NULL, NULL),
	(264, 'Miltinho Vilas Boas', NULL, NULL, NULL, NULL, NULL, NULL, 'minerobnd57@gmail.com', NULL, NULL, 'Miltinho', 'Facco', NULL, NULL),
	(265, 'Miriam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85718380', NULL, 'Miriam', 'Facco', NULL, NULL),
	(266, 'Mirian Tejada', NULL, NULL, NULL, NULL, NULL, NULL, 'mirian.tejada@bol.com.br', NULL, NULL, 'Mirian', 'Facco', NULL, NULL),
	(267, 'MITHRA rock band', NULL, NULL, NULL, NULL, NULL, NULL, 'aguiargh@gmail.com', NULL, NULL, 'MITHRA', 'Facco', NULL, NULL),
	(268, 'Monique Perez', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05182854502', NULL, 'Monique', 'Facco', NULL, NULL),
	(269, 'Moto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98887595', NULL, 'Moto', 'Facco', NULL, NULL),
	(270, 'Nair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4896093360', NULL, 'Nair', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNair.jpg'),
	(271, 'Natalia Granitoff - Complex', NULL, NULL, NULL, NULL, NULL, NULL, 'natalia@thecomplex.com.br', '96484783', '30621869', 'Natalia Granitoff', 'Facco', '92566558', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNatalia Granitoff - Complex.jpg'),
	(272, 'Natha', NULL, NULL, NULL, NULL, NULL, NULL, 'natha.57@gmail.com', '5193879363', NULL, 'Natha', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNatha.jpg'),
	(273, 'natha andrades', NULL, NULL, NULL, NULL, NULL, NULL, 'natha.57@gmail.com', NULL, NULL, 'natha', 'Facco', NULL, NULL),
	(274, 'Neusa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34699414', NULL, 'Neusa', 'Facco', NULL, NULL),
	(275, 'Nilo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05133915568', NULL, 'Nilo', 'Facco', NULL, NULL),
	(276, 'Nilton Silva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '011966236656', NULL, 'Nilton', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNilza.jpg'),
	(277, 'Nilza', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33666330', '81522861', 'Nilza', 'Facco', NULL, NULL),
	(278, 'Notebook - Patricia', 'Betnardinho Silveira Amorim Padaria Prospera', 3695, NULL, NULL, NULL, NULL, 'pattys_cardoso@hotmail.com', '93493732', '37796963', 'Notebook', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNotebook - Patricia.jpg'),
	(279, 'Odair Vargas Alves', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '73109095', NULL, 'Odair', 'Facco', NULL, NULL),
	(280, 'Odair Luis Pocai de Mello', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5199640556', NULL, 'Odair Luis Pocai', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesOdair Luis Pocai de Mello.jpg'),
	(281, 'Odete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4836267399', NULL, 'Odete', 'Facco', NULL, NULL),
	(282, 'Odon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96426165', NULL, 'Odon', 'Facco', NULL, NULL),
	(283, 'OI - Paulo RM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85955577', NULL, 'OI -', 'Facco', NULL, NULL),
	(284, 'Oi - Benhur RM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84482312', NULL, 'Oi - Benhur', 'Facco', NULL, NULL),
	(285, 'Oi - Ederson RM - Internet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Oi - Ederson', 'Facco', NULL, NULL),
	(286, 'OI - Renata Investicon', NULL, NULL, NULL, NULL, NULL, NULL, 'renata@investicon.com.br', '84949990', '32876655', 'OI - Renata', 'Facco', NULL, NULL),
	(287, 'OI - Suporte Empresarial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '08000310800', NULL, 'OI - Suporte', 'Facco', NULL, NULL),
	(288, 'Oliria Concato', NULL, NULL, NULL, NULL, NULL, NULL, 'oliriaconcato@hotmail.com', '33667961', '91646737', 'Oliria', 'Facco', '82831107', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesOliria Concato.jpg'),
	(289, 'Oliveira Rober', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Oliveira', 'Facco', NULL, NULL),
	(290, 'Oneides/fernanda riboli', NULL, NULL, NULL, NULL, NULL, NULL, 'oneidesriboli@yahoo.com.br', NULL, NULL, 'Oneides/fernanda', 'Facco', NULL, NULL),
	(291, 'Osmar Emilio Rodrigues', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81417775', NULL, 'Osmar', 'Facco', NULL, NULL),
	(292, 'Ouvidoria SUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05132885800', NULL, 'Ouvidoria', 'Facco', NULL, NULL),
	(293, 'Pai Douglas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '93661948', NULL, 'Pai', 'Facco', NULL, NULL),
	(294, 'Pai Do Douglas Ace', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85649670', NULL, 'Pai Do', 'Facco', NULL, NULL),
	(295, 'Paola Nunes', 'Rua Congonhas', 16, NULL, NULL, NULL, NULL, 'lety_57_gatinha@hotmail.com', '05134715446', '05184766667', 'Paola', 'Facco', '05194168071', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPaola Nunes.jpg'),
	(296, 'Patricia Facco', 'Rua Sete de Setembro', 146, 'Vila Jardim América', 'Cachoeirinha', 'RS', '94920-630', 'patricia.acfacco@gmail.com', '84721051', '98545-6568', 'patricia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPatrícia Facco.jpg'),
	(297, 'Paula Galvan da Rosa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91843829', NULL, 'Paula Galvan', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPaula Galvan da Rosa.jpg'),
	(298, 'Paulinho', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98123601', NULL, 'Paulinho', 'Facco', NULL, NULL),
	(299, 'Paulo Habitasul', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96928477', '34691013', 'Paulo', 'Facco', NULL, NULL),
	(300, 'Paulo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34707178', NULL, 'Paulo', 'Facco', NULL, NULL),
	(301, 'Paulo Casa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33966300', '98882283', 'Paulo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPaulo Casa.jpg'),
	(302, 'PAULO CESAR BRAGA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PAULO CESAR', 'Facco', NULL, NULL),
	(303, 'Paulo Cesar Dias Gomes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Paulo Cesar', 'Facco', NULL, NULL),
	(304, 'Paulo Mileski - Volpato', NULL, NULL, NULL, NULL, NULL, NULL, 'paulomileski@terra.com.br', '81499434', NULL, 'Paulo Mileski', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPaulo Mileski - Volpato.jpg'),
	(305, 'Paulo Roberto Alves Machado- Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85363239', '05134698610', 'Paulo Roberto Alves', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPaulo Roberto Alves Machado- Cliente.jpg'),
	(306, 'Pedro Gomes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pedro', 'Facco', NULL, NULL),
	(307, 'plinio simon', NULL, NULL, NULL, NULL, NULL, NULL, 'pjplinio@gmail.com', NULL, NULL, 'plinio', 'Facco', NULL, NULL),
	(308, 'Priscilla Amaral', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Priscilla', 'Facco', NULL, NULL),
	(309, 'Rafael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33875537', NULL, 'Rafael', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRafael.jpg'),
	(310, 'Rafael da Silva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05185583666', NULL, 'Rafael', 'Facco', NULL, NULL),
	(311, 'Rafael Macedo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '96234671', NULL, 'Rafael', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRafael Macedo.jpg'),
	(312, 'Rafael Davi Martins Costa', 'Rua dos Andradas', 2, NULL, 'Porto Alegre', 'RS', NULL, 'rafaeldmc@terra.com.br', '30619910', '30618810', 'Rafael Davi', 'Facco', '84287735', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRafael Davi Martins Costa.jpg'),
	(313, 'Rafaela Concato Facco Silva', NULL, NULL, NULL, NULL, NULL, NULL, 'rafaelaconcato@gmail.com', '94267310', NULL, 'Rafaela', 'Facco', NULL, NULL),
	(314, 'Rainer', 'Botafogo', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '93844363', '998816804', 'Rainer', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRainer.jpg'),
	(315, 'Raphael - Karin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34698968', '99004045', 'Raphael', 'Facco', '86541307', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRaphael - Karin.jpg'),
	(316, 'Regina', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05193522325', NULL, 'Regina', 'Facco', NULL, NULL),
	(317, 'Reinoldo Mello', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Reinoldo', 'Facco', NULL, NULL),
	(318, 'roberto alvares de brito', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'roberto', 'Facco', NULL, NULL),
	(319, 'Roberto', 'Petropolis', 670, NULL, NULL, NULL, NULL, NULL, '05192333859', NULL, 'Roberto', 'Facco', NULL, NULL),
	(320, 'Rodolfo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81497232', NULL, 'Rodolfo', 'Facco', NULL, NULL),
	(321, 'Rodrigo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '99330219', NULL, 'Rodrigo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRodrigo.jpg'),
	(322, 'Rodrigo Brasil Ribeiro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rodrigo Brasil', 'Facco', NULL, NULL),
	(323, 'Rogeni Vinicius Mattivi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '35627410', '05193652450', 'Rogeni', 'Facco', '81199407', NULL),
	(324, 'Roger Rubin', 'Rua Do Cedro  Sapucaia RS Brasil', NULL, NULL, NULL, NULL, NULL, 'roger.silva@rbstv.com.br', '34525119', '33207082', 'Roger', 'Facco', NULL, NULL),
	(325, 'Rogerio - RS Transportes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '95389467', NULL, 'Rogerio -', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRogerio - RS Transportes.jpg'),
	(326, 'Ronaldo Serralheria Panoram', 'Rua Emília Gaúna Bochehin', 542, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-545', NULL, '34411362', '5191063260', 'Ronaldo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRonaldo Medeiros.jpg'),
	(327, 'Rosana Passos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rosana', 'Facco', NULL, NULL),
	(328, 'Rose', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85249274', NULL, 'Rose', 'Facco', NULL, NULL),
	(329, 'Roselaine - Campanella', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98168600', NULL, 'Roselaine', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRoselaine - Campanella.jpg'),
	(330, 'Rubens de Castro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11983232656', NULL, 'Rubens', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRubens de Castro.jpg'),
	(331, 'SAIMON SANTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SAIMON', 'Facco', NULL, NULL),
	(332, 'Sandra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34381428', NULL, 'Sandra', 'Facco', NULL, NULL),
	(333, 'Sandra - Pet Shop', 'Rua Flamengo', 88, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-130', NULL, '5134692424', '92533968', 'Sandra -', 'Facco', '91491622', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSandra - PetShop.jpg'),
	(334, 'Saraah Luanee', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '92325092', NULL, 'Saraah', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSaraah Luanee.jpg'),
	(335, 'Seguro Moto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '40044100', '08007255901', 'Seguro', 'Facco', '93282384', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSeguro Moto.jpg'),
	(336, 'Seguro Carro - Rafael', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '+55 51 84470775', '35939933', 'Seguro Carro', 'Facco', '05184470489', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSeguro Carro - Rafael.jpg'),
	(337, 'Seguro Carro Fabiano', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '32194757', '92811274', 'Seguro Carro', 'Facco', NULL, NULL),
	(338, 'Senai', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05192355015', NULL, 'Senai', 'Facco', NULL, NULL),
	(339, 'shana beatriz', NULL, NULL, NULL, NULL, NULL, NULL, 'shanabeatrizr@hotmail.com', NULL, NULL, 'shana', 'Facco', NULL, NULL),
	(340, 'Sibila Amiga Da Dede', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '89302315', NULL, 'Sibila Amiga', 'Facco', NULL, NULL),
	(341, 'Silvana Goulart', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5196689898', NULL, 'Silvana', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSilvana Goulart.jpg'),
	(342, 'Silvana Regina Pires', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Silvana Regina', 'Facco', NULL, NULL),
	(343, 'Silvio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33667961', '33432100', 'Silvio', 'Facco', '92115236', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSilvio.jpg'),
	(344, 'Simone', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34697724', NULL, 'Simone', 'Facco', NULL, NULL),
	(345, 'Sirlene Souza de Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84206110', NULL, 'Sirlene Souza', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSirlene Souza de Oliveira.jpg'),
	(346, 'SIRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '91797725', NULL, 'SIRO', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSIRO.jpg'),
	(347, 'Solange - Padaria Padre Réus', 'Av.Panamericana', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-330', 'sol.nassar@hotmail.com', '(51)3469-2685', '(51)99263-1874', 'Solange', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSolange.jpg'),
	(348, 'Sonia - Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34696960', '99142293', 'Sonia', 'Facco', NULL, NULL),
	(349, 'Sony - Anec Service', 'Rua Alberto Bins', 585, NULL, 'Porto Alegre', 'Rs', NULL, NULL, '33398844', NULL, 'Sony -', 'Facco', NULL, NULL),
	(350, 'stefano oliveira', NULL, NULL, NULL, NULL, NULL, NULL, 'stefanoedf@gmail.com', NULL, NULL, 'stefano', 'Facco', NULL, NULL),
	(351, 'Suh Pereira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05194272701', '05194079010', 'Suh', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSuh Pereira.jpg'),
	(352, 'Supermercado Colonial', NULL, NULL, NULL, NULL, NULL, NULL, 'supercolonial.extratos@gmail.com', '3469-2588', '3469-0935', 'Diego', 'Facco', NULL, NULL),
	(353, 'Susana Avila', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '85977015', '05191713700', 'Susana', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSusana Avila.jpg'),
	(354, 'Suzete Pizzio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Suzete', 'Facco', NULL, NULL),
	(355, 'Tabelinato 49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34702630', NULL, 'Tabelinato', 'Facco', NULL, NULL),
	(356, 'Taiy Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0155596948183', '0215599261178', 'Taiy', 'Facco', NULL, NULL),
	(357, 'Tatiane Melo Ferreira', 'Rua Uruguai', 245, NULL, NULL, NULL, NULL, 'tatianne.melo@hotmail.com', '92522025', NULL, 'Tatiane', 'Facco', NULL, NULL),
	(358, 'Taxi Tavares', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34383323', '96399347', 'Taxi', 'Facco', NULL, NULL),
	(359, 'Telmo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5198419805', NULL, 'Telmo', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesTelmo.jpg'),
	(360, 'Thais Bernsmuller', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '94393889', NULL, 'Thais', 'Facco', NULL, NULL),
	(361, 'Thiago Pinheiro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34716334', NULL, 'Thiago', 'Facco', NULL, NULL),
	(362, 'Tia Marga', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05193445577', NULL, 'Tia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesTia Marga.jpg'),
	(363, 'Tia Ana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33340784', '82691303', 'Tia Ana', 'Facco', NULL, NULL),
	(364, 'Tia Rose', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '30297232', '92954435', 'Tia Rose', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesTia Rose.jpg'),
	(365, 'Tiago GIP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34697337', NULL, 'Tiago', 'Facco', NULL, NULL),
	(366, 'Tio Pedro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4834389384', '4896406085', 'Tio', 'Facco', NULL, NULL),
	(367, 'Tio Vilmar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4896035649', NULL, 'Tio', 'Facco', NULL, NULL),
	(368, 'Vagner Duprat Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11973878983', NULL, 'Vagner', 'Facco', NULL, NULL),
	(369, 'Vanda', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4896439515', NULL, 'Vanda', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVanda.jpg'),
	(370, 'Vanessa Remedi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '80118302', '84423557', 'Vanessa', 'Facco', '81083285', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVanessa Remedi.jpg'),
	(371, 'Vanessa J. Carvalho', 'Cachoeirinha - RS', NULL, NULL, NULL, NULL, NULL, NULL, '5191284787', NULL, 'Vanessa J.', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVanessa J. Carvalho.jpg'),
	(372, 'Varlei Pinheiro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11987041672', NULL, 'Varlei', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVarlei Pinheiro.jpg'),
	(373, 'Vera', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34722095', '34763489', 'Vera', 'Facco', '91549273', NULL),
	(374, 'Vicente Vommaro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21984203776', NULL, 'Vicente', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVicente Vommaro.jpg'),
	(375, 'Vilmar Dupark Serigrafia Carla', 'Rua Madureira', 179, NULL, NULL, NULL, NULL, NULL, '34696850', NULL, 'Vilmar', 'Facco', NULL, NULL),
	(376, 'Vistoria Do Carro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05192553450', NULL, 'Vistoria', 'Facco', NULL, NULL),
	(377, 'Vitor Eduardo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '82492569', NULL, 'Vitor', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVitor Eduardo.jpg'),
	(378, 'viviani marcelo de castro vivi', NULL, NULL, NULL, NULL, NULL, NULL, 'vivianimarcelo@gmail.com', NULL, NULL, 'viviani', 'Facco', NULL, NULL),
	(379, 'Volpato', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '33425551', '40639025', 'Volpato', 'Facco', NULL, NULL),
	(380, 'Wagner Cesar dos Santos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Wagner', 'Facco', NULL, NULL),
	(381, 'Walter Ernesto Basilio Bermudes', 'Rua Buarque de Macedo', 872, NULL, 'Porto Alegre', 'RS', NULL, NULL, '33433055', '99676140', 'Walter Ernesto', 'Facco', NULL, NULL),
	(382, 'WILLIAM GOMES', NULL, NULL, NULL, NULL, NULL, NULL, 'williamgomes_rg@hotmail.com', '85845457', '94056114', 'WILLIAM', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesWILLIAM GOMES.jpg'),
	(383, 'Wizard - Tatiana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '84790089', '92622721', 'Wizard', 'Facco', NULL, NULL),
	(384, 'Empresa Construtora Ernesto Woebcke S.A.', 'RS-030, 2038', 1140, 'Parque Itatiaia', 'Gravatai', 'RS', '94180-130', 'contabilidade@woebcke.com.br', '33422911', '99988245', 'Edith', 'Facco', '99717054', 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesWoebcke.jpg'),
	(385, 'Yaskara Concato', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '81421116', NULL, 'Yaskara', 'Facco', NULL, NULL),
	(386, 'Yuri', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '05134411792', NULL, 'Yuri', 'Facco', NULL, NULL),
	(387, 'Zoleide', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '34412693', NULL, 'Zoleide', 'Facco', '91395422', NULL),
	(388, 'Zoltan Guilherme Geocze', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '11971976800', NULL, 'Zoltan Guilherme', 'Facco', NULL, NULL),
	(389, 'Helma', 'Rua Barão de Cotejipe', 122, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', NULL, NULL, '(51)84544998', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesHelma - Cliente.jpg'),
	(390, 'Leila - Cliente', 'Rua Tijuca', 1218, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '8494-7075', 'Leila', 'Facco', NULL, NULL),
	(392, 'Iris - Cliente', 'Diadema', 165, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '91020440', '93349580', 'Iris', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesIris.jpg'),
	(393, 'Cris Gomes - Ciana', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '98543381', NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCris Gomes - Ciana.jpg'),
	(394, 'Ju - Papelaria', 'Itaqui', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, NULL),
	(395, 'Brito', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '3469-1193', '8260-3376', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBrito.jpg'),
	(396, 'Gabriela Cândido - Lucia', 'Av.Panamericana', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950330', NULL, '3469-0235', '9781-9902', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesGabriela Cândido - Lucia.jpg'),
	(397, 'Maria da Graça - Advogada', 'AvAsssis Brasil - Sala 303', 2187, 'Cristo Redentor', 'Porto Alegre', 'RS', NULL, 'dra.graca@hotmail.com', '3343-6976', '9901-4050', 'Dra.Graça', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMaria Da Graça - Advogada.jpg'),
	(398, 'Bete - Costureira mãe da Raquel', 'Av.Panameriana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, NULL),
	(399, 'Eduardo - Visinho', 'Botafogo', 690, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', NULL, NULL, NULL, NULL, 'Facco', NULL, NULL),
	(400, 'Katia - comidas', 'Botafogo', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', NULL, '3438-7628', NULL, NULL, 'Facco', NULL, NULL),
	(401, 'Vladmir Dornellas', 'Rua Tijuca', 1380, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVladimir Dornellas.jpg'),
	(402, 'Carolina - Alvarez', 'Rua Santa Cecilia', 157, 'Vila City', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '9363-0678', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCarol - Alvarez.jpg'),
	(403, 'Vânia - Cliente', 'Rua Copacabana', 186, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '5192459675', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVânia - Cliente.jpg'),
	(404, 'Bibiana - Pisicóloga', 'Hospital Cristo Redentor', NULL, 'Cristo Redentor', 'Porto Aelgre', 'RS', NULL, NULL, '3357-4124', '8418-9498', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBibiana - Psicóloga.jpg'),
	(405, 'Christiano  Schürer', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, 'chris.schurer@gmail.com', NULL, '92101238', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesBanda Mithra.jpg'),
	(406, 'Mateus Pacheco', 'Rua Ribeirão Preto', 46, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-460', NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMateus Pacheco.jpg'),
	(407, 'Lidiane Rossato', NULL, NULL, NULL, 'Porto Alegre', 'RS', NULL, NULL, NULL, '84242522', NULL, 'Facco', NULL, NULL),
	(408, 'Dany / Xandy - Padaria', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '84614326', NULL, 'Facco', NULL, NULL),
	(409, 'Gonçalves - Seg.do Diego', 'Rua Emíia Gaúna', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '86332214', NULL, 'Facco', NULL, NULL),
	(410, 'Andreia Rachel Aguiar Schurer', 'Rua Bento Gonçalves', 1325, 'Apto: 02', 'Esteio', 'RS', '93265-350', 'andreiashurer@gmail.com', NULL, '8046-6600', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndréia - Irmã Do Cris.jpg'),
	(411, 'Jéssica', 'Av.Panamericana', 724, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-330', NULL, NULL, '85638662', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJéssica.jpg'),
	(412, 'Pamêla - Tia da Desiree', 'Rua Manoel Almeida', 71, 'Bela Vista', 'Alvorada', 'RS', '94810-350', NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPamêla - Prima da Desiree.jpg'),
	(413, 'Tales Correa TG', 'Rua Mogi Mirim', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '86664970', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesTales Correa TG.jpg'),
	(414, 'Edi - Cliente', 'Rua Botafogo', 621, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-080', NULL, NULL, '8563-8500', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEdi - Cliente.jpg'),
	(415, 'Patrícia - Cliente', 'Rua Imbuí', 1328, 'Vlia Cachoeirinha', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '85107590', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPatrícia - Cliente.jpg'),
	(416, 'Wilson - Cliente', 'Rua Botafogo', 674, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '34692271', NULL, NULL, 'Facco', NULL, NULL),
	(417, 'Nilson Rodeski', 'Rua Santa Cecilia', 517, 'Vila City', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '99998381', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNilson - Alvarez.jpg'),
	(418, 'Juliana Nunes Maria', 'Rua Bonsucesso', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJuliana Nunes Maria.jpg'),
	(419, 'Marcia Elisa Gonçalves Rodrigues', 'Rua Dr.João César Krieger', 109, 'Rubem Berta', 'Porto Alegre', 'RS', '91180-185', NULL, '9665-1260', '3348-6178', 'Marcia', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarcia.jpg'),
	(420, 'Carmen Comerlato Nicolau', 'Rua Diadema', 71, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '3020-7302', '8609-2407', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCarmen Comerlato Nicolau.jpg'),
	(421, 'Juarez', 'Rua Carlos Gomes, 1265', NULL, 'Vila Tupã', 'Alvorada', 'RS', '94824-380', NULL, '89315273', NULL, 'Juarez', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJuarez.jpg'),
	(422, 'Fabricio Chagas - Fafa', 'Rua Porto Rico', 1530, 'Americana', 'Alvorada', 'RS', NULL, NULL, NULL, '93875325', 'Fafa1530', NULL, NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFabricio Chagas - Fafa.jpg'),
	(423, 'Flávia', 'Escola Desiree', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFlávia Deia Ferreira.jpg'),
	(424, 'Maicon', 'Rua Botafogo', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMaicon Silveira.jpg'),
	(425, 'Fernanda', 'Escola Roberto Silveira', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFernanda Gouveia.jpg'),
	(426, 'Emerson', 'Rua Cascavel', 570, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-540', NULL, NULL, '85387545', NULL, 'Facco', NULL, NULL),
	(427, 'Vanessa Russi Fiorini', 'Rua Gaston Englert', 574, 'Vila Ipiranga', 'Porto Alegre', 'RS', '91360-210', 'vanessarussifiorini@hotmail.com', NULL, '99805-3639', 'Vanessa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesVanessa (Bibi).jpg'),
	(428, 'Lucia Candido', 'Av.Panmericana', 900, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-330', NULL, NULL, '8126-4275', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLucia Candido.jpg'),
	(429, 'Homero - Fabrica de móveis São José', 'Av.Circular, 941', NULL, 'Jardim Itú Sabará', 'Porto Alegre', 'RS', NULL, NULL, '3334-4307', '9309-1098', NULL, 'Facco', NULL, NULL),
	(430, 'Maiga - Cabeleireira', 'Paranavai', 175, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-440', 'maigacabeleireira@gmail.com', '3469-0203', '98438-2474', 'Maiga', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMaiga - Cabeleireira.jpg'),
	(431, 'Karen Regina Alves', 'Rua Guaporé', 30, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-150', 'karenreginaalves@hotmail.com', NULL, '8920-7596', 'Karen', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesKaren Regina Alves.jpg'),
	(432, 'Agostinho Montanha Garcez', 'Rua Copacabana', 26, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-575', NULL, '3471-8037', '9190-6119', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAgostinho Montanha Garcez.jpg'),
	(433, 'Joyce Führ - Cliente', 'Rua Cel.João Pacheco de Freitas', 529, 'Jardim Itú Sabará', 'Porto Alegre', 'RS', '91215-060', 'joycestan789@hotmail.com', '99278-8341', '98507-1836', 'Joyce', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJoyce Führ.jpg'),
	(434, 'Raquel - cliente', 'Rua Diadema', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '98499-9817', 'Raquel', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRaquel.jpg'),
	(435, 'Andriele Santos', NULL, NULL, 'Americana', 'Alvorada', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndriele Santos.jpg'),
	(436, 'Pâmela - Funcionária JAJA', 'Iguatemi', 76, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '99224-7969', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPâmela.jpg'),
	(437, 'Filho do Cara da Casinha da Bruxa', 'Rua Itaqui, esquina Panamericana', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '991703904', NULL, 'Facco', NULL, NULL),
	(438, 'Cristina Schiavi', 'Rua Roque Calage - Apto.801', 566, 'Passo da areia', 'Porto Alegre', 'RS', '91350-090', NULL, '32731667', '99341-1741', 'Cristina', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCristina - Cliente.jpg'),
	(439, 'Rosane - Cliente', 'Rua Iguatemi', 166, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-470', NULL, '3041-2392', '99842-0109', 'Rô', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRosangela - Cliente.jpg'),
	(440, 'Jair Santos - Jaja Churrasquinhos', 'Rua Barão de Cotegipe', 215, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', NULL, '99116-5542', '98409-1945', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJair Santos.jpg'),
	(441, 'Diego - ACE', 'Rua Copacabana', 135, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-575', NULL, '3137-4415', '8932-6767', 'Diego', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDiego - ACE.jpg'),
	(442, 'Maria Talmazir Nobre dos Santos', 'Rua Carlos Trein Filho - Apto 402', 266, 'Auxiliadora', 'Porto Alegre', 'RS', '90450-120', NULL, NULL, '99841-9488', 'Dona Palma', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPalma.jpg'),
	(443, 'Auber Brum', 'Capacabana', 195, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-575', NULL, '34693978', NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAuber.jpg'),
	(444, 'Estauber', 'Rua Palmas - Condomínio Maranhão', 24, 'Jardim Betânia', 'Cachoeirinha', 'RS', '95970-535', NULL, NULL, '984240392', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesStauber.jpg'),
	(445, 'Empresa Construtora Ernesto Woebeck - Gravatai', 'RS 30', 2038, 'Sítio Sobrado', 'Gravataí', 'RS', '94180-130', NULL, '3488-6400', NULL, 'Talles / Alexandre', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesWoebcke.jpg'),
	(446, 'Cesar Ribeiro Prates', 'Rua Botafogo', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '95950-080', 'cesarribeiroprates@gmail.com', NULL, '982590863', 'Cesar', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCesar Ribeiro Prates.jpg'),
	(447, 'Mauricio - Bela Gula', 'Av.Assis Brasil', 4320, 'São Sebastião', 'Porto Alegre', 'RS', '91110-000', NULL, '3737-8737', '992493549', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMauricio - Bela Gula.jpg'),
	(448, 'Everton - Cliente', 'Av. Eng.José Maria de Carvalho', 46, 'Vila Ipiranga', 'Porto Alegre', 'RS', '91360-080', NULL, NULL, '98178-8499', 'Everton', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEverton - Cliente.jpg'),
	(449, 'Rosana - Cliente', 'Rua Paranavai', 106, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-440', NULL, NULL, '99112-1632', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRosana - Clente.jpg'),
	(450, 'Marcelo Pasqual - Marcelo Gás', 'Av.Panemericana', 867, 'Parque da Matriz', 'Cachoeirinha', 'RS', '95950-330', 'mppasqual.marcelo@gmail.com', '3471-6171', '98410-2630', 'pw: 18536372mp', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarcelo Pasqual - Marcelo Gás.jpg'),
	(451, 'Rosemary Santos', 'Rua Gaspar Martins', NULL, 'Americana', 'Alvorada', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRosemary Santos.jpg'),
	(452, 'Cler', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '992199215', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCler.jpg'),
	(453, 'Eduardo Mendonça', 'Rua Poços de Caldas', 154, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-340', NULL, NULL, '99761-7160', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEduardo Mendonça.jpg'),
	(454, 'Ruth Helena Dutra Klein', 'Rua Poços de Caldas', 154, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-340', 'ruthhklein@hotmail.com', NULL, '99870-0354', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRuth Helena Dutra Klein.jpg'),
	(455, 'Vilmar', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '99257-9070', NULL, 'Facco', NULL, NULL),
	(456, 'Patrick', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '99764-0527', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPatrick.jpg'),
	(457, 'Nira - Nayara', 'Rua Barão de Cotagipe', 11, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', NULL, NULL, '984533856', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNira - Nayara.jpg'),
	(458, 'Marcia - Escola Oliria', NULL, NULL, NULL, 'Porto Alegre', 'RS', NULL, NULL, '993353119', '992250678', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMarcia - Escola Oliria.jpg'),
	(459, 'Nayara Canals', 'Rua Barão de Cotegipe, 11', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-050', NULL, NULL, '985425852', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesNayara Canals.jpg'),
	(460, 'Simone', 'Mario Totta', 1060, 'Americana', 'Alvorada', 'RS', '94820-401', NULL, NULL, '985457643', 'Simone', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSimone Cliente.jpg'),
	(461, 'Mauro Coin', 'Rua Iguatemi', 125, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-470', NULL, '3438-8214', '99812-7776', 'Esposa', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMauro Coin.jpg'),
	(462, 'Eloir Acosta Lopes', 'Rua Botafogo', 666, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-080', NULL, '3469-2946', NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEloir Lopes Acosta.jpg'),
	(463, 'Karina Santos', 'Rua Bonsucesso', 903, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-490', NULL, '3469-3751', '98268-0041', 'Karina', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesKarina Santos.jpg'),
	(464, 'Carla - Cliente', 'Rua Itaqui', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '984989974', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCarla - Cliente.jpg'),
	(465, 'Mateus - Cliente', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '984702835', NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMathes - Cliente.jpg'),
	(466, 'Andrea Cabeleireira', 'Rua Bonsucesso', 989, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-490', NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndreia Cabeleireira - Matheus.jpg'),
	(467, 'Maria Talmazir Nobre', 'Carlos Train Filho - Ap 402', 266, 'Auxiliadora', 'Porto Alegre', 'RS', '90450-120', NULL, NULL, '998419488', 'Talma', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesTalma.jpg'),
	(468, 'Lucas Wesphal', NULL, NULL, NULL, 'Camaquã', 'RS', NULL, NULL, NULL, '(51)99560-9717', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLucas Wesphal.jpg'),
	(469, 'Cananda Leal', 'Rua Botafogo', 808, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-080', NULL, '985744168', NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCananda Leal.jpg'),
	(470, 'Sandra Guerra', 'Fernandes Vieira', 47, 'Bom Fim', 'Porto Alegre', 'RS', '90035-090', NULL, NULL, '5199840-2074', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesSandra Guerra.jpg'),
	(471, 'Jaqueline Colares da Silva - Gabi Atacado', 'Rua Anápio Gomes', 368, 'Vila Veranópolis', 'Cachoeirinha', 'RS', '94920-270', 'gabiatacado01@gmail.com', '51 3041-3717', NULL, 'Jaqueline', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJaqueline Colares da Silva.jpg'),
	(472, 'James Brum', 'Rua Maracanã', 50, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '(51)98484-7303', 'James', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJames.jpg'),
	(473, 'Cristina G. Barbosa', 'Rua General Vitorino', 191, 'Morada do Vale II', 'Gravatai', 'RS', '94120-330', 'cristina.g.barbosa@gmail.com', NULL, '(51)98184-9565', 'Cris', NULL, NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCristina G. Barbosajpg.jpg'),
	(474, 'Richard', 'Pacaembu', 424, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-320', NULL, NULL, '(51)98908-4786', 'Richard', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRichard.jpg'),
	(475, 'Fernanda - Cliente', 'Rua Poços de Caldas', 25, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-340', NULL, NULL, '(51)99305-7961', 'Fernanda', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesFernanda - Cliente.jpg'),
	(476, 'Jairo Maidana Bastos', 'Rua Gonçalves de Magalhães', 626, 'Jardim Porto Alegre', 'Alvorada', 'RS', '94850-520', NULL, NULL, '(51)98117-4033', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJairo Maidana Basto.jpg'),
	(477, 'Mary - Maicon', 'Rua Botafogo', 737, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-080', NULL, NULL, '(51)99125-3341', 'Mary', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesMary - Maicon.jpg'),
	(478, 'Edilaine - Didi', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '(51)99114-9325', 'Facco', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesEdilaine - Didi.jpg'),
	(479, 'Camila Ávila', 'Travessa Serafim Terra', 245, 'Jardim Botânico', 'Porto Alegre', 'RS', '90690-280', NULL, NULL, '(51)99823-4525', 'Camila', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCamila Ávila.jpg'),
	(480, 'Andre Junior Nassar dos Santos', 'Av.Panamericana', 905, 'Parque da Matriz', 'Cachoeirinha', 'RS', '95940-330', NULL, NULL, '(51)99717-3469', 'Facco', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAndré Junior - Padaria.jpg'),
	(481, 'Ledio Machado', 'Paranavai', 46, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-440', NULL, '3469-1908', '99881-1961', 'Machado', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesLedio Machado.jpg'),
	(482, 'Jorge Souza Rosa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '98444-7879', NULL, NULL, NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesJorge Souza Rosa.jpg'),
	(483, 'Rafael Brigoni', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, '98128-1222', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRafale Brigoni - Colonial.jpg'),
	(484, 'Denise Schneider', 'Rua Bonsucesso', NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, NULL, NULL, NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesDenise Schneider.jpg'),
	(485, 'Pastelaria Canto do Gaúcho', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '34691064', '997752090', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesPastelaria canto do Gaúcho.jpg'),
	(486, 'Alviete Scheffer', 'Rua Bauru', 145, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-510', NULL, NULL, '(51)99933-1492', 'Alviete', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesAlviete Scheffer.jpg'),
	(487, 'Regina Theodoro', NULL, NULL, 'Parque da Matriz', 'Cachoeirinha', 'RS', NULL, NULL, '(51)9352-2325', '(51)9984-3741', NULL, 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesRegina Theodoro.jpg'),
	(488, 'Camila Labres', 'Rua Cascavél', 530, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950-430', NULL, NULL, '(51)99882-7417', 'Camila', 'Facco', NULL, 'C:UsersJFaccoDocumentsConnectRegistro de OcorrênciasClientesCamila Labres.jpg'),
	(489, 'João Luis Facco Silva', 'Rua Botafogo', 700, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', 'jfacco@gmail.com', '(51)3137-4391', '(51)994255928', NULL, 'Connect', 'Casa', ''),
	(490, 'João Luis Facco Silva', 'Rua Botafogo', 700, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', 'jfacco@gmail.com', '(51)3137-4391', '(51)99425-5928', NULL, 'Facco', 'Casa', ''),
	(491, 'João Luis Facco Silva', 'Rua Botafogo', 700, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', 'jfacco@gmail.com', '', '', NULL, 'Connect', 'casa', ''),
	(492, 'João Luis Facco Silva', 'Rua Botafogo', 700, 'Parque da Matriz', 'Cachoeirinha', 'RS', '94950080', 'jfacco@gmail.com', '51 31374391', '51994255928', NULL, 'Connect', 'Casa', '');
/*!40000 ALTER TABLE `clientes` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
